DROP TABLE IF EXISTS img;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE img (
  id SERIAL PRIMARY KEY,
  owner_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  given_title TEXT,
  img_data BYTEA NOT NULL,
  file_type TEXT NOT NULL,
  public BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY (owner_id) REFERENCES users (id)
)